name: DOKKU-Home-Site

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: Fetching dependencies
        run : go get -v -t -d ./...
      - name: Execute test
        run : make test
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@solarch.work:22/solarch.work'
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
          branch: main